// src/data/products.ts
export interface Product {
  id: number;
  name: string;
  category: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  image: string;
  badge?: 'Sale' | 'New' | 'Best Seller' | 'Trending';
  description?: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: 'Wireless Bluetooth Headphones',
    category: 'Electronics',
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.5,
    reviews: 120,
    image: '/images/products/headphones.jpg',
    badge: 'Sale',
    description: 'High-quality wireless headphones with noise cancellation and long battery life.',
  },
  {
    id: 2,
    name: 'Smartwatch Fitness Tracker',
    category: 'Electronics',
    price: 129.99,
    originalPrice: 149.99,
    rating: 4.0,
    reviews: 80,
    image: '/images/products/smartwatch.jpg',
    badge: 'New',
    description: 'Track your fitness, heart rate, and notifications with this sleek smartwatch.',
  },
  {
    id: 3,
    name: 'Leather Sneakers',
    category: 'Footwear',
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.7,
    reviews: 200,
    image: '/images/products/sneakers.jpg',
    badge: 'Best Seller',
    description: 'Comfortable and stylish leather sneakers perfect for everyday wear.',
  },
  {
    id: 4,
    name: 'Men’s Casual Jacket',
    category: 'Fashion',
    price: 89.99,
    rating: 4.3,
    reviews: 60,
    image: '/images/products/jacket.jpg',
    badge: 'Trending',
    description: 'Lightweight, versatile jacket ideal for casual outings and travel.',
  },
  {
    id: 5,
    name: 'Gaming Mouse RGB',
    category: 'Electronics',
    price: 49.99,
    originalPrice: 59.99,
    rating: 4.6,
    reviews: 150,
    image: '/images/products/mouse.jpg',
    badge: 'Sale',
    description: 'Ergonomic gaming mouse with customizable RGB lighting and programmable buttons.',
  },
  {
    id: 6,
    name: 'Women’s Handbag',
    category: 'Fashion',
    price: 69.99,
    rating: 4.2,
    reviews: 90,
    image: '/images/products/handbag.jpg',
    badge: 'New',
    description: 'Elegant handbag made of premium materials, perfect for any occasion.',
  },
  {
    id: 7,
    name: 'Wireless Earbuds',
    category: 'Electronics',
    price: 39.99,
    originalPrice: 59.99,
    rating: 4.4,
    reviews: 180,
    image: '/images/products/earbuds.jpg',
    badge: 'Sale',
    description: 'Compact earbuds with superior sound quality and long battery life.',
  },
  {
    id: 8,
    name: 'Yoga Mat Non-Slip',
    category: 'Sports',
    price: 29.99,
    rating: 4.8,
    reviews: 220,
    image: '/images/products/yogamat.jpg',
    badge: 'Best Seller',
    description: 'Durable and non-slip yoga mat for all types of exercises and stretches.',
  },
  {
    id: 9,
    name: 'Coffee Maker Automatic',
    category: 'Home Appliances',
    price: 99.99,
    originalPrice: 129.99,
    rating: 4.5,
    reviews: 75,
    image: '/images/products/coffeemaker.jpg',
    badge: 'New',
    description: 'Brew delicious coffee quickly with this automatic coffee maker.',
  },
  {
    id: 10,
    name: 'LED Desk Lamp',
    category: 'Home',
    price: 24.99,
    rating: 4.6,
    reviews: 130,
    image: '/images/products/desklamp.jpg',
    badge: 'Trending',
    description: 'Adjustable LED desk lamp with brightness control and sleek design.',
  },
  {
    id: 11,
    name: 'Bluetooth Speaker',
    category: 'Electronics',
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.7,
    reviews: 200,
    image: '/images/products/speaker.jpg',
    badge: 'Best Seller',
    description: 'Portable Bluetooth speaker with rich sound and long battery life.',
  },
  {
    id: 12,
    name: 'Women’s Running Shoes',
    category: 'Footwear',
    price: 89.99,
    originalPrice: 109.99,
    rating: 4.4,
    reviews: 95,
    image: '/images/products/womenshoes.jpg',
    badge: 'Sale',
    description: 'Lightweight running shoes designed for comfort and performance.',
  },
  {
    id: 13,
    name: 'Men’s Leather Belt',
    category: 'Fashion',
    price: 29.99,
    rating: 4.3,
    reviews: 50,
    image: '/images/products/belt.jpg',
    badge: 'New',
    description: 'Classic leather belt that complements casual and formal outfits.',
  },
  {
    id: 14,
    name: 'Electric Kettle',
    category: 'Home Appliances',
    price: 34.99,
    rating: 4.5,
    reviews: 110,
    image: '/images/products/kettle.jpg',
    badge: 'Trending',
    description: 'Fast-boiling electric kettle with auto shut-off feature.',
  },
  {
    id: 15,
    name: 'Laptop Backpack',
    category: 'Accessories',
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.6,
    reviews: 140,
    image: '/images/products/backpack.jpg',
    badge: 'Best Seller',
    description: 'Durable backpack with padded laptop compartment and multiple pockets.',
  },
  {
    id: 16,
    name: 'Portable Power Bank',
    category: 'Electronics',
    price: 29.99,
    rating: 4.7,
    reviews: 180,
    image: '/images/products/powerbank.jpg',
    badge: 'Sale',
    description: 'High-capacity power bank to charge devices on the go.',
  },
  {
    id: 17,
    name: 'Sunglasses UV Protection',
    category: 'Fashion',
    price: 19.99,
    rating: 4.2,
    reviews: 60,
    image: '/images/products/sunglasses.jpg',
    badge: 'New',
    description: 'Stylish sunglasses with 100% UV protection.',
  },
  {
    id: 18,
    name: 'Camping Tent 4-Person',
    category: 'Sports',
    price: 129.99,
    rating: 4.5,
    reviews: 70,
    image: '/images/products/tent.jpg',
    badge: 'Trending',
    description: 'Easy-to-set-up 4-person camping tent, waterproof and durable.',
  },
  {
    id: 19,
    name: 'Fitness Dumbbell Set',
    category: 'Sports',
    price: 79.99,
    rating: 4.8,
    reviews: 120,
    image: '/images/products/dumbbell.jpg',
    badge: 'Best Seller',
    description: 'Adjustable dumbbell set perfect for home workouts.',
  },
  {
    id: 20,
    name: 'Women’s Casual T-Shirt',
    category: 'Fashion',
    price: 24.99,
    rating: 4.3,
    reviews: 90,
    image: '/images/products/tshirt.jpg',
    badge: 'New',
    description: 'Soft cotton casual T-shirt in multiple colors.',
  },
  {
    id: 21,
    name: 'Electric Toothbrush',
    category: 'Home Appliances',
    price: 39.99,
    originalPrice: 49.99,
    rating: 4.5,
    reviews: 80,
    image: '/images/products/toothbrush.jpg',
    badge: 'Sale',
    description: 'Rechargeable electric toothbrush with multiple cleaning modes.',
  },
  {
    id: 22,
    name: 'Gaming Keyboard RGB',
    category: 'Electronics',
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.6,
    reviews: 150,
    image: '/images/products/keyboard.jpg',
    badge: 'Best Seller',
    description: 'Mechanical keyboard with customizable RGB lighting and fast response.',
  },
];
